language: php

php:
  - '7.3'
  - '7.4'
  - '8.0'

install: composer install

script: make

jobs:
  include:
    - name: Test with lowest dependency versions
      install: composer update --prefer-lowest

cache:
  directories:
    - $HOME/.composer/cache/files
